


/**
 * Payload for email OTP verfication
 * Checks the pin entered by user
 * against the OTP sent to user's email
 */
export interface IEmailOtpPayload
{
  email:string; // email of user
  enteredPin?:string; // pin entered by user
}

/**
 * Payload for email OTP validation
 * Contains JWT token for email verification
 */
export interface IEmailOtpValidationpPayload
{
  jwtToken:string; // JWT token for email verification
}

export interface IEmailChallengeResponse
{
  email:string; // email of user
  sent:boolean; // true if email was sent
}
export interface IEmailOtpVerificationResponse
{
  email:string; // email of user
  verified:boolean; // true if OTP was verified
  message?:string; // message for user
  jwtToken?:string; // JWT token if OTP was verified
}
export interface IEmailOtpPendingChallenge extends IEmailChallengeResponse
{
    otp:string; // otp sent to user
    createdAt:Date; // date when challenge was created
    expiresAt:Date; // date when challenge expires
    attempts:number; // number of attempts to enter OTP
    verified:boolean; // true if OTP was verified
    jwtToken?:string; // JWT token if OTP was verified
}

/**
 * Interface for email credentials
 * Used to store email and creation date
 * This is payloaad of JWT token generated by email auth provider
 */
export interface IEmailCredentials
{
  email:string; // email of user
 createdAt:Date;
  
}
